server:
  #服务端口
  port: 8089
spring:
  datasource:
    #mysql数据库连接地址
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT
    #mysql数据用户名称
    username: root
    #mysql数据库密码
    password: 123456
  redis:
    #Redis数据库索引
    database: 0
    #Redis服务器地址
    host: 123.207.70.170
    #Redis服务器端口
    port: 6379
    #Redis密码
    password: 123456
    #自动重连时间
    timeout: 0ms
    #
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
mybatis:
  type-aliases-package: com.hpm.blog.model
  config-location: classpath:mybatis.xml
# 打印sql
logging:
  level:
    com.hpm.blog.mapper : debug